AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentConfigurationMetadata: 
  Description: Configuration created from the EB CLI using "eb config save".
EnvironmentTier: 
  Name: WebServer
  Type: Standard
SolutionStack: 64bit Amazon Linux 2015.09 v2.0.4 running Docker 1.7.1
OptionSettings: 
  aws:autoscaling:asg: 
    Cooldown: '120'
    MaxSize: '10'
    MinSize: '1'
  aws:autoscaling:launchconfiguration: 
    EC2KeyName: default
    IamInstanceProfile: EbApp
    InstanceType: m1.small
    RootVolumeSize: '80'
    RootVolumeType: gp2
    SecurityGroups: prod-yourstackhere
  aws:autoscaling:trigger: 
    BreachDuration: '1'
    LowerThreshold: '20'
    MeasureName: CPUUtilization
    Period: '1'
    Unit: Percent
    UpperBreachScaleIncrement: '2'
    UpperThreshold: '50'
  aws:autoscaling:updatepolicy:rollingupdate: 
    PauseTime: PT6M
    RollingUpdateEnabled: false
  aws:elasticbeanstalk:application: 
    Application Healthcheck URL: "/up/elb"
  aws:elasticbeanstalk:application:environment: 
   MIX_ENV: prod
   ROLE: app
  aws:elasticbeanstalk:command: 
    BatchSize: '100'
    BatchSizeType: Percentage
    Timeout: '600'
  aws:elasticbeanstalk:hostmanager: 
    LogPublicationControl: true
  aws:elasticbeanstalk:sns:topics: 
    Notification Endpoint: ''
  aws:elb:healthcheck: 
    Interval: '30'
    UnhealthyThreshold: '2'
  aws:elb:loadbalancer: 
    CrossZone: true
  aws:elb:policies: 
    ConnectionDrainingEnabled: true
    ConnectionDrainingTimeout: '20'
Tags: 
  Cluster: prod-appname
  Role: prod-appname-role-s1
